name: Vercel Deployment

env:
  VERCEL_ORG_ID: ${{ secrets.VERCEL_ORG_ID }}
  VERCEL_PROJECT_ID: ${{ secrets.VERCEL_PROJECT_ID }}

on:
  workflow_dispatch:
    inputs:
      env:
        description: 'Environment to deploy to'
        required: true
        type: choice
        options:
          - stage
          - prod
        default: stage
      tag:
        description: "Git tag to deploy (e.g., v1.2.3 or v1.2.3-rc.1)"
        required: true
        type: string


jobs:
  Vercel-Deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          ref: ${{ inputs.tag }}
      
      - name: Check node version
        run: node -v

      - name: Install Vercel CLI
        run: npm install --global vercel@latest

      - name: Pull Vercel Environment Information
        run: vercel pull --yes --environment=${{ inputs.env }} --token=${{ secrets.VERCEL_TOKEN }}

      - name: git log
        run: git log -1

      - name: Build Project Artifacts
        run: vercel build --target=${{ inputs.env }} --token=${{ secrets.VERCEL_TOKEN }}

      - name: Deploy Project Artifacts to Vercel
        run: vercel deploy --prebuilt --target=${{ inputs.env }} --token=${{ secrets.VERCEL_TOKEN }}

